### ISSUE TITLE
Openbaar maken repo (publicatie naar NPM mislukt)

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/modules-utils#10]
Wil je deze repo openbaar zetten @MartijnvDijk Hierdoor mislukt publicatie naar NPM. Ik weet ook niet waarom hij private staat, voor zover ik weet was deze eerder openbaar? Kun je daar in een log iets van vinden?

**Comment by MartijnvDijk** [comment]
Audit log laat alleen activiteit zien van de laatste 3 maanden: 'By default, only events from the past three months are displayed'.

In de afgelopen 3 maanden is niet terug te vinden dat de access van public naar private is veranderd.

Beide repo's zijn weer teruggezet naar Public.
